theme: jekyll-theme-minimal
title: Joshua's homepage
description: Bookmark this to keep an eye on my project updates!

permalink: pretty

collections_dir: collections

collections:
# Portfolio Collections ---------------
  games:
    output: true
    permalink: /games/:name/
  projects:
    output: true
    permalink: /projects/:name/
  software:
    output: true
    permalink: /software/:name/
  homepage:
    output: false
    permalink: /homepage/:name/

# D&D Collections ---------------
  acknowledgements:
    output: true
    permalink: /dnd/acknowledgements/:name/
  classes:
    output: true
    permalink: /dnd/classes/:name/
  subclasses:
    output: true
    permalink: /dnd/subclasses/:name/
  items:
    output: true
    permalink: /dnd/items/:name/
  spells:
    output: true
    permalink: /dnd/spells/:name/
  races:
    output: true
    permalink: /dnd/races/:name/
  feats:
    output: true
    permalink: /dnd/feats/:name/
  house-rules:
    output: true
    permalink: /dnd/house-rules/:name/
  reworks:
    output: true
    permalink: /dnd/reworks/:name/
  tools:
    output: true
    permalink: /dnd/tools/:name/
  content:
    output: true
    permalink: /dnd/content/:name/

defaults:
  # Portfolio Defaults ---------------
  - scope: { type: games }
    values: { layout: portfoliobase }
  - scope: { type: projects }
    values: { layout: portfoliobase }
  - scope: { type: software }
    values: { layout: portfoliobase }
  - scope: { type: homepage }
    values: { layout: portfoliobase }

  # D&D Defaults ---------------
  - scope: { type: acknowledgements }
    values: { layout: dnd }
  - scope: { type: classes }
    values: { layout: dnd }
  - scope: { type: subclasses }
    values: { layout: dnd }
  - scope: { type: items }
    values: { layout: dnd }
  - scope: { type: spells }
    values: { layout: dnd }
  - scope: { type: races }
    values: { layout: dnd }
  - scope: { type: feats }
    values: { layout: dnd }
  - scope: { type: house-rules }
    values: { layout: dnd }
  - scope: { type: reworks }
    values: { layout: dnd }
  - scope: { type: tools }
    values: { layout: dnd }
  - scope: { type: content }
    values: { layout: dnd }